### PR TITLE
PCA and Karhunen-Loeve

### LINKED ISSUE #15: Research options for dimensionality reduction
start with PCA and work towards more generic nonlinear methods (maybe based on local sensitivity analysis)

### PR DESCRIPTION
**Pull request by krystophny**
This PR adds options for principal component analysis and Karhunen-Loeve expansion. Fixes #15.

### CODE REVIEW

**Comment by krystophny** [comment]
@mkendler the basic feature and API for linear dimension reduction is now done. In the future we can use this to fit not entries of `y` output vectors with N support points of independent variables, but the lower-dimensional `z` with n entries quantifying the contribution of each eigenvector (new features) over input parameters.

In addition, I started doing docs in numpy style, which I find nicer to look at inside code than the unreadable sphinx tags. What do you think?

**Comment by krystophny** [comment]
PS: Maybe we should rather switch to Google style and https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html

**Comment by Rykath** [comment]
My two cents concerning Docstrings: I personally quite like type annotations directly in code (PEP 484 / PEP 526). While this separates the type annotation from the documentation it is very helpful when working with IDEs. It seems to me that numpy style wouldn't work that well then and Google or the default style would work better.

**Comment by krystophny** [comment]
Okay, I also think that type annotations in the code are nice and will be supported more and more in the future. For me the shape of matrices is more important, as anyone should guess that the arguments are numpy arrays or floats. So I'll play a bit with this and see how it looks.

**Review by mkendler — APPROVED** [review]

**Pull request merged**
